### ISSUE TITLE
Adding "User" as an autocmd event will not work

### ISSUE THREAD

**Issue by charbelnicolas** [natecraddock/sessions.nvim#4]
Hello @natecraddock, I know you said you don't use neovim anymore but I have a few questions and I was hoping you could please help me.

I'm using workspaces.nvim and sessions.nvim to manage my projects in neovim. So far I've had no real issues until today. This is what I'm using as a trigger to save the session.

```
require("sessions").setup({
	events = { "BufEnter" },
	session_filepath = vim.fn.stdpath("data") .. "/sessions",
	absolute = true
})
```

This works most of the time but is not the best solution. I want to save the session when a new buffer is added and when a buffer is deleted. So far I can save the session when adding buffers without any issues. The problem is when deleting the buffers, there is no actual way in neovim to know if a buffer has been deleted with an autocmd event.

This is where https://github.com/famiu/bufdelete.nvim comes in handy. It has an autocmd User event called BDeletePre and BDeletePost.

```
User autocommands

bufdelete.nvim triggers the following User autocommands (see :help User for more information):

BDeletePre {range_start,range_end} - Prior to deleting a buffer.
BDeletePost {range_start,range_end} - After deleting a buffer.

In both of these cases, range_start and range_end are replaced by the start and end of the buffer range, respectively.
For example, if you use require('bufdelete').bufdelete({1, 42}), the autocommand patterns will be BDeletePre {1,42} and BDeletePost {1,42}.
```
Now, if I add the "User" event like this:

```
require("sessions").setup({
	events = { "BufEnter", "User" },
	session_filepath = vim.fn.stdpath("data") .. "/sessions",
	absolute = true
})
```
That won't work. 

If I add this code to `sessions.nvim/lua/sessions/init.lua` then it does work:

```
-- start autosaving changes to the session file
local start_autosave = function()
    -- save future changes
    local events = vim.fn.join(config.events, ",")
    local augroup = vim.api.nvim_create_augroup("sessions.nvim", {})
    vim.api.nvim_create_autocmd(
        string.format("%s", events),
        {
            group = augroup,
            pattern = "*",
            callback = write_session_file,
        }
    )
    vim.api.nvim_create_autocmd(
        string.format("%s", "User"),
        {
            group = augroup,
            pattern = "*",
            callback = write_session_file,
        }
    )

    -- save now
    write_session_file()
end
```
Do you know what I need to do to make it work without editing the plugin's source code? I'm a total noob when it comes to plugins or autocmds so any help is really appreciated. Thank you.

P.S. I loved your work on blender's outliner BTW ;)

**Comment by natecraddock** [comment]
Hi @charbelnicolas, I'm happy to take a look at this over the next few days. I've got a lot of other things going on, but I'll take a look as soon as I am able!

> P.S. I loved your work on blender's outliner BTW ;)

Haha, small world! It was fun, and I wish I had the time to contribute to Blender some more :)

**Comment by charbelnicolas** [comment]
Hey @natecraddock, thanks for taking the time. BTW, I don't know for sure if there is a need to do the event join step:

```
local events = vim.fn.join(config.events, ",")
```

I modified the ```init.lua``` file like this and it works:

```
-- start autosaving changes to the session file
local start_autosave = function()
    -- save future changes
    local augroup = vim.api.nvim_create_augroup("sessions.nvim", {})
    vim.api.nvim_create_autocmd(
        config.events,
        {
            group = augroup,
            pattern = "*",
            callback = write_session_file
        }
    )

    -- save now
    write_session_file()
end
```
Now I can use this:

```
require("sessions").setup({
	events = { "BufEnter", "User" },
	session_filepath = vim.fn.stdpath("data") .. "/sessions",
	absolute = true
})
```
Maybe it was a quick fix after all?

**Comment by natecraddock** [comment]
Hi @charbelnicolas! Sorry I let this slip by the last few days.

It looks like when I updated this to use the new nvim_create_autocmd API I didn't remove the string join (which was needed when running a string as vimscript). I just pushed a fix based on your suggestions that should help! Let me know if that doesn't work.

Thanks for catching this!

**Comment by natecraddock** [comment]
I'm going to close this (assuming the issue is truly resolved). Please let me know if it isn't!

**Comment by charbelnicolas** [comment]
Everything is working as expected, thank you! I still have some modifications I made myself for my neovim config but everything is working like it should.
